#!/usr/bin/env sh

usage() {
	echo "usage:"
	echo "    $0 [options] <command>"
	echo ""
	echo "where options are empty or a combination of:"
	echo "    -h, --help         print this help"
	echo ""
	echo "This software is developed at https://github.com/llenck/swapify"
	exit 0
}

( [ "$1" = "--help" ] || [ "$1" = "-h" ]; ) && usage

INSTALLED_PATH="/lib/libswapify.so"
LOCAL_PATH="$PWD/libswapify.so"

if [ -f "$INSTALLED_PATH" ]; then
	LIB_PATH="$INSTALLED_PATH"
elif [ -f "$LOCAL_PATH" ]; then
	LIB_PATH="$LOCAL_PATH"
else
	echo "Error: couldn't find libswapify.so"
	exit 1
fi

# lazy loading tends so segfault (in do_lookup_x from ld.so), so set LD_BIND_NOW
LD_BIND_NOW=1 LD_PRELOAD="$LIB_PATH" exec "$@"

# if we're here, exec hasn't worked
usage
